name: ETL-Automatico-Salesforce

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar Solicitud de matricula - Descargar
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python etl/procesos/solicitud_matricula/01_descargar.py

    - name: Ejecutar Solicitud de matricula -Transformacion
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python etl/procesos/solicitud_matricula/02_transformacion.py

    - name: Ejecutar Solicitud de matricula -Carga
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python etl/procesos/solicitud_matricula/03_carga.py

    - name: Ejecutar Asistencia Extracurricular - Descargar
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python etl/procesos/asistencia_extracurricular/01_descarga.py

    - name: Ejecutar Asistencia Extracurricular - Transformacion
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python etl/procesos/asistencia_extracurricular/02_transformacion.py

    - name: Ejecutar Asistencia Extracurricular - Carga
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      run: python etl/procesos/asistencia_extracurricular/03_carga.py

    - name: Subir archivo final como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: asistencia_extracurricular
        path: salida/asistencias_extracurriculares/asistencias_extra_consolidado_kantaya.csv


    - name: Subir artefacto del DF final
      uses: actions/upload-artifact@v4
      with:
        name: df-final-salesforce
        path: debug/df_final_a_subir.csv

      
    - name: Subir artefactos de salida
      uses: actions/upload-artifact@v4
      with:
        name: salida-etl-solicitud-matricula
        path: |
          salida/


