name: ETL-Automatico-Salesforce

on:
  #schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
    
  # ============================================================
  # 🔹 ASISTENCIA REGULAR
  # ============================================================

    #- name: Ejecutar Asistencia Regular - Descargar
    #  env:
    #    GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #  run: python etl/procesos/asistencia_regular/01_descargar.py

    #- name: Ejecutar Asistencia Regular - Transformación
    #  run: python etl/procesos/asistencia_regular/02_transformacion.py

    #- name: Ejecutar paso 3 - Subir a Salesforce de asistencia regular
    #  run: python etl/procesos/asistencia_regular/03_carga.py

  # ============================================================
  # 🔹 ASISTENCIA EXTRACURRICULAR
  # ============================================================

    #- name: Asistencia Extracurricular - Descargar
    #  env:
    #    GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #  run: python etl/procesos/asistencia_extracurricular/01_descarga.py

    #- name: Asistencia Extracurricular - Transformación
    #  run: python etl/procesos/asistencia_extracurricular/02_transformacion.py

    #- name: Asistencia Extracurricular - Carga
    #  run: python etl/procesos/asistencia_extracurricular/03_carga.py

  # ============================================================
  # 🔹 MATRÍCULA
  # ============================================================

    #- name: Ejecutar Matricula - Descarga
    #  env:
    #    GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #  run: python etl/procesos/matricula/01_descarga.py

    #- name: Ejecutar Matricula -Transformacion
    #  env:
    #    GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #  run: python etl/procesos/matricula/02_transformacion.py

    #- name: Ejecutar Matricula -Carga
    #  env:
    #    GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #  run: python etl/procesos/matricula/03_carga.py

 # ============================================================
 # 🔹 CALIFICACIONES ÁREA COMPETENCIA
 # ============================================================

    #- name: Calificaciones Área Competencia - Descargar
    #  env:
    #    SHAREPOINT_HOSTNAME: kantaya.sharepoint.com
    #    SHAREPOINT_SITE_PATH: /sites/EducativoKantaya
    #    SHAREPOINT_FILE_NAME: Comparativa_Ventanilla y proyectos_Power BI Provisional.xlsx
    #  run: python "etl/procesos/2025/4. calificaciones_area_competencia/01_descarga.py"

    #- name: Calificaciones Área Competencia - Transformación
    #  run: python "etl/procesos/2025/4. calificaciones_area_competencia/02_transformacion.py"


    
    # ============================================================
    # 🔹 Artefactos
    # ============================================================
         
    - name: Listar archivos generados
      run: |
        ls -R data/raw || true
        ls -R data/processed || true

    #- name: Subir artefactos de salida - Extracurricular
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: asistencias-extracurriculares-consolidada
    #    path: salida/asistencias_extracurriculares/*

    #- name: Subir artefactos de salida - Asistencia regular
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: asistencias-regular-consolidada
    #    path: salida/asistencias/*

    #- name: Subir artefactos de salida - Matrícula
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: matricula-consolidada
    #    path: salida/matricula/*

    #- name: Subir artefacto raw - Calificaciones Área Competencia
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: calificaciones-area-competencia-raw
    #    path: data/raw/2025/4.calificaciones_area_competencia/*

    #- name: Subir artefacto processed - Calificaciones Área Competencia
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: calificaciones-area-competencia-processed
    #    path: data/processed/2025/4.calificaciones_area_competencia/*

